### ISSUE TITLE
中文规则

### ISSUE THREAD

**Issue by eduosi** [xsec-lab/xsec-waf-docs#1]
您好。请问一下，我在 post 规则中，新增了一个中文规则，如：澳门博彩，为什么不生效呢？是不支持中文规则么？

**Comment by netxfly** [comment]
我空了调试一下，看看是不是被转码了，

**Comment by netxfly** [comment]
在管理端中添加完后再去看看服务器中rules目录中有吗？如果没有，可能管理端没有写rules目录的权限或者reload权限。
