### ISSUE TITLE
关于app.ini

### ISSUE THREAD

**Issue by shuncon** [xsec-lab/xsec-waf-docs#3]
首先非常感谢gay主的开源，非常感谢！
问题：
使用mariadb创建wafadmin用户后，在app.ini中修改：
[database]
USER = wafadmin
PASSWD = shunconf
#PASSWD = password
HOST = 127.0.0.1:3306
NAME = waf
然后./server启动后登录管理后台的默认的账户及口令分别为：admin，x@xsec.io， 都不行
要么提示无效的口令  要么就啥都不提示

**Comment by netxfly** [comment]
请确认下数据库能否正常连接：）
